# launch-claude.ps1
# Generated by Domitek Secrets Manager v1.5
# Project: __PROJECT_NAME__
# Copyright (c) 2026 Domitek. All rights reserved. scan.domitek.ai
# =============================================================
# USAGE:
#   .\launch-claude.ps1             -- loads secrets + starts Claude Code
#   .\launch-claude.ps1 -NoLaunch  -- loads secrets only (for VS Code/Cursor)
# =============================================================
param([switch]$NoLaunch)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$PROJECT_NAME = "__PROJECT_NAME__"

$KEYS = @(
__KEYS__
)

$NEXT_PUBLIC_KEYS = @(
__NEXT_PUBLIC_KEYS__
)

Write-Host ""
Write-Host "Domitek Secrets Manager" -ForegroundColor White
Write-Host "-----------------------------------------" -ForegroundColor DarkGray
Write-Host "Project: $PROJECT_NAME" -ForegroundColor Cyan
Write-Host "Loading secrets from Windows Credential Manager..." -ForegroundColor Gray
Write-Host ""

$missing = @()
foreach ($key in $KEYS) {
    $target = "${PROJECT_NAME}_${key}"
    try {
        $cred = Get-StoredCredential -Target $target
        if ($null -eq $cred) {
            $missing += $key
            Write-Host "  x Missing: $key" -ForegroundColor Red
        } else {
            $value = $cred.GetNetworkCredential().Password
            [System.Environment]::SetEnvironmentVariable($key, $value, "Process")
            if ($key -in $NEXT_PUBLIC_KEYS) {
                [System.Environment]::SetEnvironmentVariable("NEXT_PUBLIC_$key", $value, "Process")
            }
            Write-Host "  + Loaded:  $key" -ForegroundColor Green
        }
    } catch {
        $missing += $key
        Write-Host "  x Error:   $key" -ForegroundColor Red
    }
}

Write-Host ""
if ($missing.Count -gt 0) {
    Write-Host "  Warning: $($missing.Count) secret(s) not found in vault." -ForegroundColor Yellow
    Write-Host "  Open Secrets Manager to add them." -ForegroundColor Gray
    Write-Host ""
}

Write-Host "All available secrets loaded into session memory." -ForegroundColor Green
Write-Host "Nothing written to disk." -ForegroundColor Gray
Write-Host "Secrets expire when this terminal session closes." -ForegroundColor Gray
Write-Host ""

# =============================================================
# Generate .domitek-secrets.md  (full DSM reference -- fully owned by DSM)
# =============================================================
$secretsDoc = Join-Path $PSScriptRoot ".domitek-secrets.md"
$keysLoaded = $KEYS | Where-Object { $_ -notin $missing }

$docLines = @()
$docLines += "# Domitek Secrets Manager"
$docLines += ""
$docLines += "This file is auto-generated. Do not edit manually."
$docLines += "Regenerate by running ``launch-claude.ps1`` or using the Secrets Manager GUI."
$docLines += ""
$docLines += "## Project"
$docLines += ""
$docLines += "- Name: $PROJECT_NAME"
$docLines += "- Managed by: Domitek Secrets Manager v1.5"
$docLines += ""
$docLines += "## Environment Variables"
$docLines += ""
$docLines += "All secrets are injected at startup via Windows Credential Manager."
$docLines += "Available as environment variables. Use the exact names listed below with ``process.env``."
$docLines += ""
$docLines += "### Available variables this session"
$docLines += ""
if ($keysLoaded.Count -gt 0) {
    foreach ($k in $keysLoaded) { $docLines += ("- " + $k) }
} else {
    $docLines += "- (none currently loaded -- open Secrets Manager to add keys)"
}
$docLines += ""
if ($NEXT_PUBLIC_KEYS.Count -gt 0) {
    $docLines += "### NEXT_PUBLIC_ duplicates (for Next.js client-side access)"
    $docLines += ""
    foreach ($k in $NEXT_PUBLIC_KEYS) { $docLines += ("- NEXT_PUBLIC_" + $k) }
    $docLines += ""
}
$docLines += "## Rules"
$docLines += ""
$docLines += "1. DO NOT create ``.env``, ``.env.local``, or ``.env.production`` files"
$docLines += "2. DO NOT hardcode API keys or URLs -- always use ``process.env.VARIABLE_NAME``"
$docLines += "3. For Vercel deployment: add variables in the Vercel dashboard only, never in files"
$docLines += "4. Use the exact variable names listed above"
$docLines += ""
$docLines += "## How secrets flow"
$docLines += ""
$docLines += '```'
$docLines += "Windows Credential Manager -> launch-claude.ps1 -> environment variables -> process.env"
$docLines += '```'
$docLines += ""
$docLines += "Secrets exist only in the current session's memory and expire when the terminal closes."
$docLines += ""

# Clear Hidden attribute if file already exists -- Out-File refuses to overwrite hidden files
if (Test-Path $secretsDoc) {
    try {
        $existingItem = Get-Item $secretsDoc -Force -ErrorAction Stop
        if ($existingItem.Attributes -band [System.IO.FileAttributes]::Hidden) {
            $existingItem.Attributes = $existingItem.Attributes -band (-bnot [System.IO.FileAttributes]::Hidden)
        }
    } catch {}
}

$docLines -join "`n" | Out-File -FilePath $secretsDoc -Encoding UTF8

# Set Hidden attribute on Windows (file is already dot-prefixed for macOS/Linux)
try {
    $secretsDocItem = Get-Item $secretsDoc -Force -ErrorAction Stop
    $secretsDocItem.Attributes = $secretsDocItem.Attributes -bor [System.IO.FileAttributes]::Hidden
} catch {}

Write-Host ".domitek-secrets.md updated." -ForegroundColor DarkGray

# =============================================================
# Update CLAUDE.md -- strip old Domitek section, append fresh pointer
# =============================================================
$claudeMd = Join-Path $PSScriptRoot "CLAUDE.md"

$DOMITEK_HEADING = "## Domitek Secrets (auto-generated)"
$pointer = @()
$pointer += ""
$pointer += $DOMITEK_HEADING
$pointer += "<!-- Do not edit. Regenerated by Domitek Secrets Manager. -->"
$pointer += ""
$pointer += "Secrets are injected from Windows Credential Manager at launch."
$pointer += "For full rules and available variables, see: ``.domitek-secrets.md``"
$pointer += ""
$pointer += "DO NOT create ``.env`` files."
$pointer += ""

$existing = ""
if (Test-Path $claudeMd) {
    $existing = [System.IO.File]::ReadAllText($claudeMd)
}

# Strip any previous Domitek section: from the heading down to the next H2 (##) or EOF.
# Uses (?ms) = multiline + dotall. The [^#\r\n] in the lookahead ensures we stop only at
# another ##-level heading, not at subheadings inside our section like ###.
$pattern = "(?ms)\r?\n?## Domitek Secrets \(auto-generated\).*?(?=\r?\n## [^#\r\n]|\z)"
$stripped = [regex]::Replace($existing, $pattern, "")
# Normalise trailing whitespace so our section always appends cleanly
$stripped = $stripped.TrimEnd()

$finalContent = if ([string]::IsNullOrWhiteSpace($stripped)) {
    ($pointer -join "`n").TrimStart()
} else {
    $stripped + "`n" + ($pointer -join "`n")
}

$finalContent | Out-File -FilePath $claudeMd -Encoding UTF8 -NoNewline
Write-Host "CLAUDE.md updated." -ForegroundColor DarkGray
Write-Host ""

Write-Host "=================================================" -ForegroundColor DarkGray
Write-Host "  REMINDER FOR CLAUDE:" -ForegroundColor Yellow
Write-Host "  Secrets are injected from Windows Credential Manager." -ForegroundColor White
Write-Host "  DO NOT create .env or .env.local files." -ForegroundColor Red
Write-Host "  For Vercel: add vars in Vercel dashboard only." -ForegroundColor White
Write-Host "  Full rules: .domitek-secrets.md" -ForegroundColor DarkGray
Write-Host "=================================================" -ForegroundColor DarkGray
Write-Host ""

if ($NoLaunch) {
    Write-Host "Secrets ready. Open Claude Code manually or use your IDE." -ForegroundColor Cyan
} else {
    Write-Host "Starting Claude Code..." -ForegroundColor Cyan
    Write-Host ""
    claude --dangerously-skip-permissions
}
