# launch-claude.ps1
# Generated by Domitek Secrets Manager v1.5
# Project: __PROJECT_NAME__
# Copyright (c) 2026 Domitek. All rights reserved. scan.domitek.ai
# =============================================================
# USAGE:
#   .\launch-claude.ps1             -- loads secrets + starts Claude Code
#   .\launch-claude.ps1 -NoLaunch  -- loads secrets only (for VS Code/Cursor)
# =============================================================
param([switch]$NoLaunch)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# Suppress the "Install the latest PowerShell" update check banner that
# PowerShell 5.1 prints at startup. Off at the process scope only -- we
# do not modify the user's PowerShell profile or any global setting.
$env:POWERSHELL_UPDATECHECK = "Off"

$PROJECT_NAME = "__PROJECT_NAME__"

$KEYS = @(
__KEYS__
)

$NEXT_PUBLIC_KEYS = @(
__NEXT_PUBLIC_KEYS__
)

Write-Host ""
Write-Host "Domitek Secrets Manager" -ForegroundColor White
Write-Host "-----------------------------------------" -ForegroundColor DarkGray
Write-Host "Project: $PROJECT_NAME" -ForegroundColor Cyan
Write-Host "Loading secrets from Windows Credential Manager..." -ForegroundColor Gray
Write-Host ""

$missing = @()
foreach ($key in $KEYS) {
    $target = "${PROJECT_NAME}_${key}"
    try {
        $cred = Get-StoredCredential -Target $target
        if ($null -eq $cred) {
            $missing += $key
            Write-Host "  x Missing: $key" -ForegroundColor Red
        } else {
            $value = $cred.GetNetworkCredential().Password
            [System.Environment]::SetEnvironmentVariable($key, $value, "Process")
            if ($key -in $NEXT_PUBLIC_KEYS) {
                [System.Environment]::SetEnvironmentVariable("NEXT_PUBLIC_$key", $value, "Process")
            }
            Write-Host "  + Loaded:  $key" -ForegroundColor Green
        }
    } catch {
        $missing += $key
        Write-Host "  x Error:   $key" -ForegroundColor Red
    }
}

Write-Host ""
if ($missing.Count -gt 0) {
    Write-Host "  Warning: $($missing.Count) secret(s) not found in vault." -ForegroundColor Yellow
    Write-Host "  Open Secrets Manager to add them." -ForegroundColor Gray
    Write-Host ""
}

Write-Host "All available secrets loaded into session memory." -ForegroundColor Green
Write-Host "Nothing written to disk." -ForegroundColor Gray
Write-Host "Secrets expire when this terminal session closes." -ForegroundColor Gray
Write-Host ""

$claudeMd = Join-Path $PSScriptRoot "CLAUDE.md"
$keysLoaded = $KEYS | Where-Object { $_ -notin $missing }
$claudeLines = @()
$claudeLines += "# Domitek Secrets -- Project: $PROJECT_NAME"
$claudeLines += ""
$claudeLines += "## Environment Variables"
$claudeLines += "All secrets are injected at startup via Windows Credential Manager."
$claudeLines += "Available as environment variables. Use the exact names listed below with process.env."
$claudeLines += ""
$claudeLines += "### Available variables this session:"
foreach ($k in $keysLoaded) { $claudeLines += ("- " + $k) }
$claudeLines += ""
$claudeLines += "## IMPORTANT RULES"
$claudeLines += "1. Never create .env or .env.local files -- secrets come from the vault"
$claudeLines += "2. Never hardcode API keys or URLs -- always use process.env.VARIABLE_NAME"
$claudeLines += "3. For Vercel deployment -- add variables in Vercel dashboard only, never in files"
$claudeLines += "4. Variable naming -- use exact names as listed above"
$claudeLines += ""
$claudeLines += "## How secrets flow"
$claudeLines += "Windows Credential Manager -> launch-claude.ps1 -> environment variables -> process.env"
$claudeLines -join "`n" | Out-File -FilePath $claudeMd -Encoding UTF8
Write-Host "CLAUDE.md updated." -ForegroundColor DarkGray
Write-Host ""

Write-Host "=================================================" -ForegroundColor DarkGray
Write-Host "  REMINDER FOR CLAUDE:" -ForegroundColor Yellow
Write-Host "  Secrets are injected from Windows Credential Manager." -ForegroundColor White
Write-Host "  DO NOT create .env or .env.local files." -ForegroundColor Red
Write-Host "  For Vercel: add vars in Vercel dashboard only." -ForegroundColor White
Write-Host "=================================================" -ForegroundColor DarkGray
Write-Host ""

if ($NoLaunch) {
    Write-Host "Secrets ready. Open Claude Code manually or use your IDE." -ForegroundColor Cyan
} else {
    Write-Host "Starting Claude Code..." -ForegroundColor Cyan
    Write-Host ""
    claude --dangerously-skip-permissions
}
